# Generated by Django 3.0.8 on 2022-01-16 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menu",
            name="date",
            field=models.DateField(unique=True),
        ),
    ]
