# Generated by Django 3.0.8 on 2022-01-18 03:37

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0002_auto_20220116_1931"),
        ("staff", "0002_auto_20220116_1931"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="menu.Product",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="menu",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="menu.Menu",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
